### ISSUE TITLE
cjs: Importing specific locale in jest test fails with 'Cannot find module'

### ISSUE THREAD

**Issue by shmuelsochet** [faker-js/faker#462]
### Describe the bug

When importing specific locale during a jest test, the test fails with the error `Cannot find module '@faker-js/faker/locale/en' from...`

### Reproduction

1. Add the line `const faker = require('@faker-js/faker/locale/en');` on top of a jest file (i.e example.test.js)
2. Run test `npm run test example.test.js
3. You should get the 'Cannot find module '@faker-js/faker/locale/en' error

### Additional Info

This does not occur when using the same import not during a jest test.
It also does not occur when not using specific locale like this `const { faker } = require('@faker-js/faker');`

**Comment by Shinigami92** [comment]
Can you try to provide a reproducible via https://stackblitz.com/edit/faker-js-demo?file=index.ts ?
Or maybe just a minimal GitHub repo

**Comment by hansonfang** [comment]
I have same issue after I upgraded it to 6.0.0 alpha. so I downgraded to 5.5.3 than problems gone.

**Comment by Shinigami92** [comment]
@shmuelsochet @hansonfang Please try out the `alpha.7` and report if the issue is fixed for you

**Comment by rich-frost** [comment]
We've noticed this issue again in version 8 when running our jest tests; error as follows:

```bash
Test suite failed to run

    Cannot find module '@faker-js/faker/locale/en' from 'node_modules/our-module/main.js
```

Have downgraded to version 7 and it works. Is this something that can be looked at in version 8?

**Comment by matthewmayer** [comment]
Can you switch to the prepackaged faker instances available in v8 eg

const { fakerEN : faker } = require('@faker-js/faker');

**Comment by rich-frost** [comment]
We have a legacy project that bundles this into the built code (work in progress to extract) so we were looking to just bring in the EN locale to reduce bundle size

**Comment by ST-DDT** [comment]
> We've noticed this issue again in version 8 when running our jest tests; error as follows:
> 
> ```shell
> Test suite failed to run
> 
>     Cannot find module '@faker-js/faker/locale/en' from 'node_modules/our-module/main.js
> ```
> 
> Have downgraded to version 7 and it works. Is this something that can be looked at in version 8?

This issue is closed and I'm unable to reproduce the error locally.

````ts
const { faker } = require("@faker-js/faker/locale/en");
console.log(typeof faker); // object
console.log(faker.person.firstName()); // Tatyana
console.log(faker.location.city()); // Fisherborough
````

Please create a [new issue](https://github.com/faker-js/faker/issues/new?assignees=&labels=s%3A+pending+triage%2Cc%3A+bug&projects=&template=bug_report.yml) and provide a minimal reproducible example.
