### PR TITLE
infra(lint): enable jsdoc-js/require-throws

### LINKED ISSUE #4021: Use oxlint to detect other places where functions throw but don't have a throws JSDoc
To catch more issues like

https://github.com/faker-js/faker/issues/4015
https://github.com/faker-js/faker/issues/4018

There's a oxlint rule

`jsdoc-js/require-throws`

If you set this to `warn` it finds 13 more places which can be investigated.

## All 13 warnings

| File | Line | Function |
|---|---|---|
| `src/internal/locale-proxy.ts` | 104 | `assertLocaleData` |
| `src/modules/commerce/module.ts` | 289 | `isbn` |
| `src/modules/helpers/eval.ts` | 67 | `fakeEval` |
| `src/modules/helpers/eval.ts` | 114 | `evalProcessFunction` |
| `src/modules/helpers/eval.ts` | 147 | `findParams` |
| `src/modules/helpers/eval.ts` | 183 | `evalProcessExpression` |
| `src/modules/helpers/module.ts` | 26 | `getRepetitionsBasedOnQuantifierParameters` |
| `src/modules/location/module.ts` | 232 | `zipCode` |
| `src/modules/phone/module.ts` | 30 | `number` |
| `src/modules/string/module.ts` | 123 | `fromCharacters` |
| `src/modules/string/module.ts` | 507 | `numeric` |
| `src/modules/system/module.ts` | 165 | `fileExt` |
| `src/modules/word/module.ts` | 340 | `sample` |

**Public API methods (8):** `isbn`, `fakeEval`, `zipCode`, `number`, `fromCharacters`, `numeric`, `fileExt`, `sample`

**Internal/private helpers (5):** `assertLocaleData`, `evalProcessFunction`, `findParams`, `evalProcessExpression`, `getRepetitionsBasedOnQuantifierParameters`

### PR DESCRIPTION
**Pull request by MahinAnowar**
Closes #4021.

Turning on `jsdoc-js/require-throws` flagged 14 functions that can throw without documenting it. I went through each one and wrote the `@throws` from the actual throw site rather than guessing at it, so the conditions match what the code really does:

| | |
|---|---|
| ~~`Faker` constructor~~ | ~~empty `locale` option~~ |
| `assertLocaleData` | locale data missing or not applicable |
| `commerce.isbn` | no registrant length for the generated group |
| `fakeEval` | expression empty or unresolvable |
| `evalProcessFunction` | unexpected character after a call |
| `findParams` | missing closing parenthesis |
| `evalProcessExpression` | empty part, or a dot with no property name |
| `getRepetitionsBasedOnQuantifierParameters` | unknown quantifier symbol |
| `location.zipCode` | no zip definition for the given state |
| `phone.number` | no definitions for the style in this locale |
| `fromCharacters` | no characters to select from |
| `system.fileExt` | unsupported mime type |
| `word.sample` | no matching word data for the locale |
| `seeded-runs` `it` helper | method not found on the module |

The rule is set to `error` rather than `warn`, per @ST-DDT's question on the issue, so new ones can't creep back in.

Two of these throw a plain `Error` rather than a `FakerError` — `phone.number()` and the seeded-runs helper. I documented them as `{Error}` instead of quietly converting them, since changing the error type is a behaviour change and belongs in its own PR if you want it.

One note on scope: CONTRIBUTING asks to keep a PR to a single module where possible, and this one can't be — the rule only goes to `error` once every site is documented, so it's all of them or none. Happy to split it up if you'd rather review it module by module.

`pnpm lint` is clean with the rule at `error`, `oxfmt --check` passes, and the touched modules' specs run 3067 passed. (`pnpm ts-check` fails on `test/simple-faker.spec.ts` with `Cannot find module '..'` both with and without this change — it needs a build first, so it's not from this.)

### CODE REVIEW

**Comment by ST-DDT** [comment]
Blocked by/Conflict with #4043

**Comment by MahinAnowar** [comment]
Good catch, and you're right — but only on one of the 14.

The overlap is just `src/faker.ts`. #4043 deletes the constructor's only throw, so once it lands the `@throws` I added there is both wrong and unnecessary: the rule won't ask for one any more. The other 13 sites don't touch anything you're changing.

Simplest is for #4043 to go first and me to rebase on top, dropping that one line. I can't sensibly drop it ahead of time, since `require-throws` at `error` would then fail on the constructor while the throw is still there on `next`.

Happy to do it the other way round if you'd rather — say the word and I'll pull `src/faker.ts` out entirely and leave the rule at `warn` in this PR, then flip it to `error` in a small follow-up after #4043. Whichever makes your review easier.

Separately, the red Codecov check doesn't look like it's about coverage — the upload sat for three minutes and exited 1, and a sibling fork PR (#4035) uploaded fine. I'll leave it; the rebase will re-run it anyway.

**Comment by Shinigami92** [comment]
> Good catch, and you're right — but only on one of the 14.
> 
> The overlap is just `src/faker.ts`. #4043 deletes the constructor's only throw, so once it lands the `@throws` I added there is both wrong and unnecessary: the rule won't ask for one any more. The other 13 sites don't touch anything you're changing.
> 
> Simplest is for #4043 to go first and me to rebase on top, dropping that one line. I can't sensibly drop it ahead of time, since `require-throws` at `error` would then fail on the constructor while the throw is still there on `next`.
> 
> Happy to do it the other way round if you'd rather — say the word and I'll pull `src/faker.ts` out entirely and leave the rule at `warn` in this PR, then flip it to `error` in a small follow-up after #4043. Whichever makes your review easier.
> 
> Separately, the red Codecov check doesn't look like it's about coverage — the upload sat for three minutes and exited 1, and a sibling fork PR (#4035) uploaded fine. I'll leave it; the rebase will re-run it anyway.

What an AI slop comment 🫠 I read until the `—` and already knew that this is a so hard AI generated answer. Also we know that already, that is the reason why @ST-DDT made his comment.

**Comment by matthewmayer** [comment]
> Blocked by/Conflict with #4043

Good catch, and you're right — probably because you're the damn maintainer.

**Comment by ST-DDT** [comment]
> Good catch, and you're right — probably because you're the damn maintainer.

Right yes, maintainer no, just a frequent contributor/the author of that PR. 🤣

**Comment by ST-DDT** [comment]
Still blocked, by #4070

- #4070

File: src/faker.ts [hunk 1]
```diff
@@ -112,6 +112,8 @@ export class Faker extends SimpleFaker {
    * Refer to the `seed()` method for more information.
    * Defaults to a random seed.
    *
+   * @throws {FakerError} If the `locale` option does not contain at least one locale definition.
```
Comment (ST-DDT) [inline src/faker.ts:115]: This is now obsolete.

**Review by ST-DDT — CHANGES_REQUESTED** [review]
Could you please update the PR, run `pnpm run generate:module-tree` and `pnpm run preflight`?

**Comment by ST-DDT** [comment]
FYI: I fixed the remaining issues to proceed with the PR.

**Review by ST-DDT — DISMISSED** [review]

**Review by ST-DDT — APPROVED** [review]

**Review by Shinigami92 — APPROVED** [review]
